/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { createAppContainer } from 'react-navigation';
import { createStackNavigator} from 'react-navigation-stack';

import FirstScreen from './components/FirstScreen';
import SecondScreen from './components/SecondScreen';
//import all the screens we are going to switch 
const App = createStackNavigator({
    FirstScreen: { screen: FirstScreen }, 
    SecondScreen: { screen: SecondScreen }, 
  },
  {
    initialRouteName: 'FirstScreen',
  }
);
export default createAppContainer(App);
